import type { Task } from '@/features/tasks/task';

export const allTasks: Task[] = [
  {
    id: '1',
    title: 'Review quarterly report',
    completed: false,
    energyLevel: 'high',
    optimalTime: '10:00 AM - 11:30 AM',
    category: 'Deep work',
    estimatedDuration: '90 min',
    context: 'work',
  },
  {
    id: '2',
    title: 'Team meeting',
    completed: false,
    energyLevel: 'medium',
    optimalTime: '1:00 PM - 2:00 PM',
    category: 'Collaboration',
    estimatedDuration: '60 min',
    context: 'work',
  },
  {
    id: '3',
    title: 'Respond to emails',
    completed: false,
    energyLevel: 'low',
    optimalTime: '4:00 PM - 5:00 PM',
    category: 'Admin',
    estimatedDuration: '45 min',
    context: 'work',
  },
  {
    id: '4',
    title: 'Brainstorm new project ideas',
    completed: false,
    energyLevel: 'high',
    optimalTime: '9:00 AM - 10:00 AM',
    category: 'Creative',
    estimatedDuration: '60 min',
    context: 'work',
  },
  {
    id: '5',
    title: 'Update project documentation',
    completed: false,
    energyLevel: 'medium',
    category: 'Admin',
    estimatedDuration: '30 min',
    context: 'work',
  },
  {
    id: '6',
    title: 'Code review',
    completed: false,
    energyLevel: 'high',
    category: 'Deep work',
    estimatedDuration: '45 min',
    context: 'work',
  },
  {
    id: '7',
    title: 'Organize digital files',
    completed: false,
    energyLevel: 'low',
    category: 'Admin',
    estimatedDuration: '20 min',
    context: 'work',
  },
  {
    id: '8',
    title: 'Morning workout',
    completed: false,
    energyLevel: 'high',
    optimalTime: '7:00 AM - 8:00 AM',
    category: 'Health',
    estimatedDuration: '45 min',
    context: 'personal',
  },
  {
    id: '9',
    title: 'Read a book',
    completed: false,
    energyLevel: 'medium',
    optimalTime: '8:00 PM - 9:00 PM',
    category: 'Leisure',
    estimatedDuration: '30 min',
    context: 'personal',
  },
  {
    id: '10',
    title: 'Family dinner',
    completed: false,
    energyLevel: 'medium',
    optimalTime: '6:30 PM - 7:30 PM',
    category: 'Social',
    estimatedDuration: '60 min',
    context: 'personal',
  },
  {
    id: '11',
    title: 'Meditation',
    completed: false,
    energyLevel: 'low',
    optimalTime: '9:30 PM - 10:00 PM',
    category: 'Wellness',
    estimatedDuration: '15 min',
    context: 'personal',
  },
  {
    id: '12',
    title: 'Learn a new language',
    completed: false,
    energyLevel: 'high',
    category: 'Learning',
    estimatedDuration: '30 min',
    context: 'personal',
  },
  {
    id: '13',
    title: 'Garden maintenance',
    completed: false,
    energyLevel: 'medium',
    category: 'Home',
    estimatedDuration: '45 min',
    context: 'personal',
  },
  {
    id: '14',
    title: 'Listen to a podcast',
    completed: false,
    energyLevel: 'low',
    category: 'Leisure',
    estimatedDuration: '25 min',
    context: 'personal',
  },
];
